<a href="https://colab.research.google.com/github/lalit784bhaiu/lalit/blob/master/numpy_complete_beginner_to_advance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#HERE IN THIS COURSE YOU WILL HAVE A COURSE FOR NUMPY FROM BEGINNNER TO ADVANCE (HOPE YOU LOVE THIS WHOLE COURSE PLAYLIST)


In [7]:
#At first we are going to learn that how we can import numpy and and how to create a array using numpy

import numpy as np 

#first method to create a array

listarray = np.array(([8,9,4,5],[2,3,4,5]))

print(listarray)

[[8 9 4 5]
 [2 3 4 5]]


In [8]:
print(listarray.size)
print(listarray.ndim)

8
2


In [9]:
# second way to create a zero array

zeros = np.zeros([4,5])
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#third way to create a identity matrix is
identity = np.identity(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# fourth way is to find the transpose of the matrix

listarray.T

array([[8, 2],
       [9, 3],
       [4, 4],
       [5, 5]])

In [10]:
for item in listarray:
  print(item)

[8 9 4 5]
[2 3 4 5]


In [11]:
listarray.max()

9

In [12]:
listarray.argmax()

1

In [17]:
arrange=np.arange(10)
print(arrange)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
x=(((([1,2,3,4],[4,5,6,7],[8,9,7,3],[1,5,6,7]))))
ar=np.array(x)
ar.sum(axis=0)


array([14, 21, 22, 21])

In [20]:
ar.sum(axis=1)

array([10, 22, 27, 19])

In [21]:
one=np.array([3,6,9])
two=np.array([3,9,8])
one+two

array([ 6, 15, 17])

In [22]:
## most important topic is to find the numbers in the array

marks=np.array([1,2,3,4,6,9,7,3,5,0])
np.where(marks>5)  #it wil give the index of the numbers present in array according to the condition given 

(array([4, 5, 6]),)